"""Mock external LLM provider. Records every byte it receives."""
import json, os, re, time, uuid, pathlib
from typing import Any, Dict, List

import httpx
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse

DATA = pathlib.Path("/data")
DATA.mkdir(parents=True, exist_ok=True)
LOG = DATA / "received.jsonl"

USE_OLLAMA = os.getenv("USE_OLLAMA", "0") == "1"
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://ollama:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:1.5b")

app = FastAPI(title="Mock external AI provider")

SENSITIVE = [
    ("EMAIL",       re.compile(r"[\w.+-]+@[\w-]+\.[\w.]{2,}")),
    ("PHONE",       re.compile(r"\+?\d[\d\s().-]{8,}\d")),
    ("PAN",         re.compile(r"\b(?:\d[ -]*?){13,19}\b")),
    ("API_KEY",     re.compile(r"\b(?:sk|rk|pk)-[A-Za-z0-9_\-]{12,}\b")),
    ("AWS_KEY",     re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("PRIVATE_KEY", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("TOKENISED",   re.compile(r"<<[A-Z_]+_[0-9a-f]{4,}>>")),
]


def _classify(text: str) -> Dict[str, int]:
    found: Dict[str, int] = {}
    for label, rx in SENSITIVE:
        n = len(rx.findall(text))
        if n:
            found[label] = n
    return found


def _record(req: Request, raw: bytes, api: str) -> Dict[str, Any]:
    body = raw.decode("utf-8", "replace")
    entry = {
        "id": uuid.uuid4().hex[:12],
        "ts": time.time(),
        "iso": time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime()),
        "api": api,
        "host": req.headers.get("host", ""),
        "path": str(req.url.path),
        "src_ip": req.headers.get("x-forwarded-for", req.client.host if req.client else ""),
        "user_agent": req.headers.get("user-agent", ""),
        "auth_present": bool(req.headers.get("authorization") or req.headers.get("x-api-key")),
        "auth_fingerprint": (req.headers.get("authorization", "") or req.headers.get("x-api-key", ""))[:18],
        "retention_hint": {
            "store": req.headers.get("x-store", ""),
            "no_train": req.headers.get("x-no-train", ""),
        },
        "bytes": len(raw),
        "observed_sensitive": _classify(body),
        "raw_body": body[:20000],
    }
    with LOG.open("a") as fh:
        fh.write(json.dumps(entry) + "\n")
    print(f"[RECEIVED] {entry['iso']} {entry['api']} {entry['bytes']}B "
          f"sensitive={entry['observed_sensitive']}", flush=True)
    return entry


def _extract_prompt(payload: Dict[str, Any]) -> str:
    msgs: List[Dict[str, Any]] = payload.get("messages") or []
    parts = []
    for m in msgs:
        c = m.get("content")
        if isinstance(c, str):
            parts.append(c)
        elif isinstance(c, list):
            for blk in c:
                if isinstance(blk, dict) and blk.get("type") == "text":
                    parts.append(blk.get("text", ""))
    for cont in payload.get("contents", []) or []:
        for p in cont.get("parts", []) or []:
            parts.append(p.get("text", ""))
    if not parts and isinstance(payload.get("prompt"), str):
        parts.append(payload["prompt"])
    return "\n".join(parts)


async def _answer(prompt: str) -> str:
    if USE_OLLAMA:
        try:
            async with httpx.AsyncClient(timeout=120) as c:
                r = await c.post(f"{OLLAMA_URL}/api/generate",
                                 json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False})
                return r.json().get("response", "").strip()
        except Exception as exc:
            return f"[mock provider: local model unavailable: {exc}]"
    n = len(prompt)
    return (f"Summary generated by the external provider. I received {n} characters "
            f"of input and have retained a copy on my side, as my terms of service allow.")


@app.post("/v1/chat/completions")
async def openai_chat(request: Request):
    raw = await request.body()
    _record(request, raw, "openai.chat.completions")
    payload = json.loads(raw or b"{}")
    text = await _answer(_extract_prompt(payload))
    return JSONResponse({
        "id": "chatcmpl-" + uuid.uuid4().hex[:16],
        "object": "chat.completion",
        "created": int(time.time()),
        "model": payload.get("model", "gpt-4o-mini"),
        "choices": [{"index": 0, "finish_reason": "stop",
                     "message": {"role": "assistant", "content": text}}],
        "usage": {"prompt_tokens": len(raw) // 4, "completion_tokens": len(text) // 4},
    })


@app.post("/v1/messages")
async def anthropic_messages(request: Request):
    raw = await request.body()
    _record(request, raw, "anthropic.messages")
    payload = json.loads(raw or b"{}")
    text = await _answer(_extract_prompt(payload))
    return JSONResponse({
        "id": "msg_" + uuid.uuid4().hex[:16],
        "type": "message", "role": "assistant",
        "model": payload.get("model", "claude-sonnet-4-6"),
        "content": [{"type": "text", "text": text}],
        "stop_reason": "end_turn",
        "usage": {"input_tokens": len(raw) // 4, "output_tokens": len(text) // 4},
    })


@app.post("/v1beta/models/{model}:generateContent")
async def gemini_generate(model: str, request: Request):
    raw = await request.body()
    _record(request, raw, "google.generateContent")
    payload = json.loads(raw or b"{}")
    text = await _answer(_extract_prompt(payload))
    return JSONResponse({"candidates": [
        {"content": {"parts": [{"text": text}], "role": "model"}, "finishReason": "STOP"}]})


@app.get("/v1/models")
async def models():
    return {"object": "list", "data": [{"id": "gpt-4o-mini", "object": "model"},
                                       {"id": "claude-sonnet-4-6", "object": "model"}]}


@app.get("/healthz")
async def healthz():
    return PlainTextResponse("ok")


@app.get("/api/received")
async def received(limit: int = 200):
    if not LOG.exists():
        return {"items": []}
    lines = LOG.read_text().splitlines()[-limit:]
    return {"items": [json.loads(x) for x in lines][::-1]}


@app.post("/api/reset")
async def reset():
    LOG.write_text("")
    return {"ok": True}


RECEIPTS = """<!doctype html><meta charset=utf-8>
<title>External provider :: what we received</title>
<style>
 body{font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#0d1117;color:#c9d1d9;margin:0;padding:24px}
 h1{font-size:20px;color:#f0f6fc;margin:0 0 4px}
 .sub{color:#8b949e;margin-bottom:20px}
 .card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:14px 16px;margin-bottom:12px}
 .meta{color:#8b949e;font-size:12px;margin-bottom:8px}
 pre{white-space:pre-wrap;word-break:break-word;margin:0;font-size:13px}
 .tag{display:inline-block;padding:1px 7px;border-radius:99px;font-size:11px;margin-right:6px}
 .bad{background:#3d1418;color:#ff7b72;border:1px solid #6e2029}
 .ok{background:#0f2f1c;color:#3fb950;border:1px solid #1f6f3f}
 mark{background:#6e2029;color:#ffdcd7;border-radius:3px;padding:0 2px}
 mark.tok{background:#12492c;color:#7ee2a8}
 button{background:#21262d;color:#c9d1d9;border:1px solid #30363d;border-radius:6px;padding:6px 12px;cursor:pointer}
</style>
<h1>External AI provider :: inbound receipts</h1>
<div class=sub>Everything below crossed the corporate perimeter and is now sitting on infrastructure you do not control.
<button onclick="fetch('/api/reset',{method:'POST'}).then(load)">clear</button></div>
<div id=out></div>
<script>
const RX=[[/(<<[A-Z_]+_[0-9a-f]{4,}>>)/g,'tok'],
          [/([\\w.+-]+@[\\w-]+\\.[\\w.]{2,})/g,''],
          [/(\\+?\\d[\\d\\s().-]{8,}\\d)/g,''],
          [/(\\b(?:sk|rk|pk)-[A-Za-z0-9_\\-]{12,}\\b)/g,''],
          [/(\\bAKIA[0-9A-Z]{16}\\b)/g,'']];
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function hl(s){s=esc(s);for(const [rx,cls] of RX){s=s.replace(rx,(m)=>`<mark class="${cls}">${m}</mark>`)}return s}
async function load(){
 const r=await fetch('/api/received');const j=await r.json();
 document.getElementById('out').innerHTML=j.items.map(i=>{
  const tags=Object.entries(i.observed_sensitive||{}).map(([k,v])=>
    `<span class="tag ${k==='TOKENISED'?'ok':'bad'}">${k} x${v}</span>`).join('')||'<span class="tag ok">no raw identifiers</span>';
  return `<div class=card><div class=meta>${i.iso} &middot; ${i.api} &middot; host=${i.host} &middot; src=${i.src_ip} &middot; ${i.bytes} bytes &middot; ua=${esc((i.user_agent||'').slice(0,60))}</div>
   <div style="margin-bottom:8px">${tags}</div><pre>${hl(i.raw_body||'')}</pre></div>`}).join('');
}
load();setInterval(load,2000);
</script>"""


@app.get("/receipts", response_class=HTMLResponse)
async def receipts():
    return RECEIPTS
